# Add 'repo' label to any root file changes (quotation required for leading asterisk)
repo:
- changed-files:
  - any-glob-to-any-file: '*'

uniconx:
- changed-files:
  - any-glob-to-any-file: src/runtime/*

unicont:
- changed-files:
  - any-glob-to-any-file: src/icont/*

uniconc:
- changed-files:
  - any-glob-to-any-file: src/iconc/*

src:
- changed-files:
  - any-glob-to-any-file: src/**/*

runtime:
- changed-files:
  - any-glob-to-any-file: src/runtime/**/*

ipl:
- changed-files:
  - any-glob-to-any-file: ipl/**/*

uni:
- changed-files:
  - any-glob-to-any-file: uni/**/*

udb:
- changed-files:
  - any-glob-to-any-file: uni/udb/**/*

gui:
- changed-files:
  - any-glob-to-any-file: uni/gui/**/*

tests:
- changed-files:
  - any-glob-to-any-file: tests/**/*

doc:
- changed-files:
  - any-glob-to-any-file: doc/**/*

plugins:
- changed-files:
  - any-glob-to-any-file: plugins/**/*

ci:
- changed-files:
  - any-glob-to-any-file: .github/**/*
