# make, test, and install Unicon Shell files
#
# see head of dist/makefile for alternatives

default : test

test :
	cd dist; $(MAKE) test

install :
	cd dist; $(MAKE) install

uninstall :
	cd dist; $(MAKE) uninstall

clean :
	cd dist; $(MAKE) clean

testlocal :
	make -f makefile.subdir test

