// Copyright (c) 1991 Microsoft Corporation. All rights reserved.

#define IDC_SELECTTEXT              101
#define IDC_ENTIRESCREEN            311
#define IDC_PARTIALSCREEN           312
#define IDC_CLIENTAREAONLY          302
#define IDC_ENTIREWINDOW            301
#define IDC_CAPTIONBARONLY          303
#define IDC_MENUBARONLY             304
#define IDC_HELP                    112
#define IDC_SINGLEWINDOW            310
#define IDC_STATUSBAR               103
#define IDC_OPTIONSBUTTON           110
#define IDC_ICONAREA                102
#define IDC_VERSION                 111
#define IDC_COPYRIGHT               114
#define IDC_PRINTER                 115
#define IDC_FILE                    116
#define IDC_BESTFIT                 119
#define IDC_STRETCHTOPAGE           120
#define IDC_SCALE                   121
#define IDC_XAXIS                   122
#define IDC_YAXIS                   201
#define IDC_DIRECTORIES             204
#define IDC_EDITFILE                502
#define IDC_GROUPBOX1               117
#define IDC_BOX2                    118
#define IDC_BOX1                    123
#define IDC_BOX3                    124
#define IDC_FILETEXT                104
#define IDC_SELECTPRINTER           105
#define IDC_BOX4                    109
#define IDC_DIVIDINGLINE            106
#define IDC_PRINTTEXT1              401
#define IDC_PRINTTEXT2              402
#define IDC_PERCENTAGE              403
#define IDC_TITLE                   125
#define IDC_TITLE2                  128
#define IDC_TITLE1                  129
#define IDC_ABOUT                   107
#define IDC_YTEXT                   202
#define IDC_XTEXT                   200
#define IDC_FOLD                    108
