P1= p1-intro.tex p1-iconOverview.tex p1-organization.tex p1-values.tex p1-strings-csets.tex p1-lists.tex p1-sets-tables.tex p1-interpreter.tex p1-exprEval.tex p1-procs-coexprs.tex p1-storage.tex p1-runTime.tex
KW=kw/figure3-2.png kw/figure4-6.png
P2=p2-preface.tex p2-compiler.tex p2-transModel.tex p2-typeTheory.tex p2-liveness.tex p2-overview.tex p2-iconcOrg.tex p2-typeInfer.tex p2-codeGen.tex p2-ctrlflow.tex p2-invoke.tex p2-codePerform.tex p2-futureWork.tex p2-iconcOpt.tex $(KW)
P3=
P4=
SRC=ib.tex preface.tex $(P1) $(P2)

ib.pdf: $(SRC)
	pdflatex ib.tex
