

UC=unicon -s

%.u: %.icn
	@$(UC) $<

%: %.u local
	-@echo "[Testing $@...]"; \
	./$@ > local/$@.out 2>&1; \
	diff -w stand/$@.std local/$@.out ; \
	rm $@

local:
	-mkdir local

.PHONY:  clean Clean TEST 

clean Clean:
	-rm -f local/*.out *.u uniclass.* $(TARGETS)

