# top-level Icon makefile, configured for Windows NT using GCC
MAKE=make
Top:
	@echo To configure sources:
	@echo    MSVC: "nmake NT-Configure" or "nmake W-Configure"
	@echo    GCC: "make NT-Configure-GCC" or "make W-Configure-GCC"
	@echo Then run "[n]make Unicon" to build everything

WUnicon:
	cd config/win32/gcc && sh msconfig.sh
	make Unicon

W-Configure-GCC:
	cd config/win32/gcc && sh w-config.sh
	echo Run "make Unicon" to build

GL-Configure-GCC:
	cd config/win32/gcc && sh gl-config.sh
	echo Run "make Unicon" to build

NT-Configure-GCC:
	cd config/win32/gcc && sh config.sh
	echo Run "make Unicon" to build

VW-Configure-GCC:
	cd src/lib/voice; $(MAKE) -f Makefile.wgcc
	cd config/win32/gcc && sh w-config.sh
	echo ICONX=wiconx >src/runtime/makefile
	echo "VOIPLIBS=../lib/libvoip.a ../lib/libjvoip.a ../lib/libjrtp.a ../lib/libjthread.a ../lib/libaudio.a -lstdc++" >>src/runtime/makefile
	echo CONSOLE=NOTHING >>src/runtime/makefile
	cat config/win32/gcc/MAKEFILE.RUN >>src/runtime/makefile
	echo "#define Audio" >>src/h/define.h
	echo "#define HAVE_VOICE" >>src/h/define.h
	@echo Now remember to add unicon/bin to your path

NT-Configure:
	cd config\win32\msvc
	config
	echo Run "nmake Unicon" to build

W-Configure:
	cd config\win32\msvc
	w-config
	echo Run "nmake Unicon" to build

Unicon: Icon-icont
	cd ipl/lib && $(MAKE)
	cd uni/unicon && $(MAKE)

Icon-icont:
	cmd /C mkicont

#	sh Icon-icont.sh

#	cd src/rtt && $(MAKE)
#	cd src/runtime && $(MAKE) interp_all
#	cd src/icont && $(MAKE)

Configure:
	copy config/unix/Config/top.mak ./Makefile
	@echo "NT makefile replaced with UNIX makefile; try again."


X-Configure:
	copy config\unix\Config\top.mak ./Makefile
	@echo "NT makefile replaced with UNIX makefile; try again."
