

test::           calc.out 
		diff calc.out calc.correct

calc.out::       calc.in calc.exe
		calc.exe < calc.in > calc.out

calc.exe::           calc.icn
		icont calc.icn

calc.icn::       calc.y
		iyacc -i calc.y

clean::          
		del *.icn *.out calc.exe 


