config:
	rm -f `cat ../Generic/hier_hitlist`
	rm -f ../../src/iconx/fxmsdos.c ../../src/iconx/fxsys.c
	cp *.h ../../src/h
	cp *.sun ../../src/iconx
	cp itest.dos ../../tests
	cp rover.dos rswitch.dos ../../src/iconx
	cp ../Generic/*.bat ../../scripts
