Clean:
	cd iyacc; make Clean
	-if [ -f unicon/makefile ]; \
	    then cd unicon && make Clean; fi
	-if [ -f ivib/makefile ]; \
		cd ivib; make Clean; fi
	-if [ -f lib/makefile ]; \
		cd lib; make Clean; fi
