#!/bin/bash -e

#DEBHELPER#

DEB_HOST_MULTIARCH=`dpkg-architecture -qDEB_HOST_MULTIARCH`

echo "patchstr libs location: /usr/lib/$DEB_HOST_MULTIARCH/unicon"

patchstr  -DPatchUnirotHere /usr/bin/iconx /usr/lib/${DEB_HOST_MULTIARCH}/unicon
patchstr  -DPatchUnirotHere /usr/bin/icont /usr/lib/${DEB_HOST_MULTIARCH}/unicon
patchstr  -DPatchUnirotHere /usr/bin/iconc /usr/lib/${DEB_HOST_MULTIARCH}/unicon
