# top-level Icon makefile, configured for Windows NT
RM=del

Top:
	@echo To configure sources:
	@echo    MSVC: "nmake NT-Configure" or "nmake W-Configure"
	@echo    GCC: "make NT-Configure-GCC" or "make W-Configure-GCC"
	@echo Then run "[n]make Unicon" to build everything

W-Configure-GCC:
	cd config/win32/gcc && sh w-config.sh
	echo Run "make Unicon" to build

GL-Configure-GCC:
	cd config/win32/gcc && sh gl-config.sh
	echo Run "make Unicon" to build

NT-Configure-GCC:
	cd config/win32/gcc && sh config.sh
	echo Run "make Unicon" to build

NT-Configure:
	echo "You better use plain CMD.EXE or all bets are off, no sh.exe"
	cd config/win32/msvc && config.bat
	echo Run "nmake Unicon" to build

W-Configure:
	cd config/win32/msvc
	w-config.bat
	cd ../../..
	echo Run "nmake Unicon" to build

Unicon:
	cd src\runtime
	$(RM) *.obj
	cd ..\..
	nmake W-Configure
	nmake Icon-icont
	cd ipl\lib
	$(MAKE)
	cd ..\..
	cd src\runtime
	$(RM) *.obj
	cd ..\..
	nmake NT-Configure
	nmake Icon-icont
	cd uni
	$(MAKE)

#
# Uniconc
#
Uniconc bin/iconc: Common
	cd src\runtime
	$(RM) *.o
	$(MAKE) comp_all_uniconc
	cd ..\iconc
	$(MAKE)
	cd ..\..

Icon-icont:
	nmake Rtt
	cd src\runtime
	nmake interp_all
	cd ..\icont
	nmake
	cd ..\..

# Common components.
Common:		src\h\define.h
	cd src\common
	$(MAKE)
	cd ..\rtt
	$(MAKE)
	cd ..\..

Rtt:
	cd src\rtt
	nmake

Configure:
	copy config/unix/Config/top.mak ./Makefile
	@echo "NT makefile replaced with UNIX makefile; try again."


X-Configure:
	copy config\unix\Config\top.mak ./Makefile
	@echo "NT makefile replaced with UNIX makefile; try again."
