# top-level Icon makefile, configured for Windows NT
Top:
	@echo To configure sources:
	@echo    MSVC: "nmake NT-Configure" or "nmake W-Configure"
	@echo    GCC: "make NT-Configure-GCC" or "make W-Configure-GCC"
	@echo Then run "[n]make Unicon" to build everything

W-Configure-GCC:
	cd config/win32/gcc && sh w-config.sh
	echo Run "make Unicon" to build

GL-Configure-GCC:
	cd config/win32/gcc && sh gl-config.sh
	echo Run "make Unicon" to build

NT-Configure-GCC:
	cd config/win32/gcc && sh config.sh
	echo Run "make Unicon" to build

NT-Configure:
	cd config\win32\msvc
	cmd /C config
	echo Run "nmake Unicon" to build

W-Configure:
	cd config\win32\msvc
	cmd /C w-config
	echo Run "nmake Unicon" to build

Unicon:
	nmake W-Configure
	nmake Icon-icont
	cd ipl\lib
	$(MAKE)
	cd ..\..
	nmake NT-Configure
	nmake Icon-icont
	cd uni
	$(MAKE)

Icon-icont:
	nmake Rtt
	cd src\runtime
	nmake interp_all
	cd ..\icont
	nmake
	cd ..\..

Rtt:
	cd src\rtt
	nmake

Configure:
	copy config/unix/Config/top.mak ./Makefile
	@echo "NT makefile replaced with UNIX makefile; try again."


X-Configure:
	copy config\unix\Config\top.mak ./Makefile
	@echo "NT makefile replaced with UNIX makefile; try again."
