# top-level Icon makefile, configured for Windows CE
Top:
	@echo To configure sources:
	@echo    MSVC: "nmake NT-Configure" or "nmake W-Configure"
	@echo    GCC: "make NT-Configure-GCC" or "make W-Configure-GCC"
	@echo    MSVC for WINCE: "nmake WCE-Configure"
	@echo Then run "[n]make Unicon" to build everything


WCE-Configure:
	cd config\winCE\msvc
	w-config
	echo Run "nmake Unicon" to build

Unicon:
	nmake WCE-Configure
	nmake Icon-icont
	cd ipl\lib
	$(MAKE)
	cd ..\..
	nmake NT-Configure
	nmake Icon-icont
	cd uni
	$(MAKE)

Icon-icont:
	nmake Rtt
	cd src\runtime
	nmake interp_all
	cd ..\icont
	nmake
	cd ..\..

Rtt:
	cd src\rtt
	nmake

Configure:
	copy config/unix/Config/top.mak ./Makefile
	@echo "NT makefile replaced with UNIX makefile; try again."


X-Configure:
	copy config\unix\Config\top.mak ./Makefile
	@echo "NT makefile replaced with UNIX makefile; try again."
