SHELL=/bin/sh
MAKE=make

what:
		@echo "what do you want to make?"


Test:
		sh Test-icont icont


##########################################################
#
#  Clean up.
#
Clean:
		rm -rf local/*
		mkdir local
		touch local/.placeholder


