SHELL=/bin/sh
MAKE=make

#what:
#		@echo "what do you want to make?"

default: Test

Test:
		sh Test-icont icont


##########################################################
#
#  Clean up.
#
Clean:
		rm -rf local/*
		-mkdir -p local
		touch local/.placeholder


