
TARGETS=$(patsubst %.icn,%,$(wildcard *.icn))

what:
		@echo "what do you want to make?"

Clean:
		rm -f $(TARGETS) *.c *.h

clean:
		@rm -f $(TARGETS) *.c *.h

distclean Dist-clean:
		rm -f .*K* .emacs*
