/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* undocumented */
/* #undef ALSA_SUPPORT */

/* undocumented */
/* #undef ARTS_SUPPORT */

/* undocumented */
#define BOMB 1

/* undocumented */
/* #undef BROKEN_LIBIO */

/* undocumented */
/* #undef BSD_TARGET */

/* undocumented */
/* #undef CAPTURE_SUPPORT */

/* undocumented */
/* #undef DARWIN_TARGET */

/* undocumented */
/* #undef DEBUG */

/* undocumented */
/* #undef DEBUG_BUFFER */

/* undocumented */
/* #undef DEBUG_CONFIG */

/* undocumented */
/* #undef DEBUG_CONTEXT */

/* undocumented */
/* #undef DEBUG_CONVERT */

/* undocumented */
/* #undef DEBUG_EXT */

/* undocumented */
/* #undef DEBUG_FILTER */

/* undocumented */
/* #undef DEBUG_LOCK */

/* undocumented */
/* #undef DEBUG_LOOP */

/* undocumented */
/* #undef DEBUG_MATH */

/* undocumented */
/* #undef DEBUG_MAXIMUS */

/* undocumented */
/* #undef DEBUG_MEM */

/* undocumented */
/* #undef DEBUG_MIXER */

/* undocumented */
/* #undef DEBUG_QUEUE */

/* undocumented */
/* #undef DEBUG_SOURCE */

/* undocumented */
/* #undef DEBUG_STREAMING */

/* undocumented */
/* #undef DEBUG_STUB */

/* undocumented */
/* #undef DMALLOC */

/* undocumented */
/* #undef DMALLOC_FUNC_CHECK */

/* undocumented */
/* #undef DSOUND_SUPPORT */

/* undocumented */
/* #undef EMPTY_LOCKS */

/* undocumented */
/* #undef ESD_SUPPORT */

/* undocumented */
/* #undef FFT */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <time.h> header file. */
/* #undef HAVE_TIME_H */

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* undocumented */
/* #undef IRIS_SUPPORT */

/* undocumented */
/* #undef IRIX_TARGET */

/* undocumented */
/* #undef JLIB */

/* undocumented */
#define LINUX_TARGET 1

/* undocumented */
/* #undef MORPHOS_TARGET */

/* undocumented */
/* #undef NODLOPEN */

/* undocumented */
/* #undef NO_THREADS */

/* undocumented */
#define NULL_SUPPORT 1

/* undocumented */
/* #undef OPENAL_DLOPEN_ALSA */

/* undocumented */
/* #undef OPENAL_DLOPEN_ARTS */

/* undocumented */
/* #undef OPENAL_DLOPEN_ESD */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "openal-devel@opensource.creative.com"

/* Define to the full name of this package. */
#define PACKAGE_NAME "OpenAL library"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "OpenAL library 0.0.8"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "openal"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.0.8"

/* undocumented */
/* #undef PARANOID_LOCKS */

/* undocumented */
#define PIC 1

/* undocumented */
#define RDYNAMIC "-rdynamic"

/* undocumented */
#define SDL_SUPPORT 1

/* The size of a `void *', as computed by sizeof. */
#define SIZEOF_VOID_P 4

/* undocumented */
#define SMPEG_SUPPORT 1

/* undocumented */
/* #undef SOLARIS_TARGET */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* undocumented */
/* #undef USE_MORPHOSMUTEX */

/* undocumented */
/* #undef USE_MORPHOSTHREADS */

/* undocumented */
#define USE_POSIXMUTEX 1

/* undocumented */
#define USE_POSIXTHREADS 1

/* undocumented */
/* #undef USE_WINDOWSMUTEX */

/* undocumented */
/* #undef USE_WINDOWSTHREADS */

/* undocumented */
#define VORBIS_SUPPORT 1

/* undocumented */
#define WAVEOUT_SUPPORT 1

/* undocumented */
/* #undef WINDOWS_TARGET */

/* Define to 1 if your processor stores words with the most significant byte
   first (like Motorola and SPARC, unlike Intel and VAX). */
/* #undef WORDS_BIGENDIAN */

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */
