# top-level Icon makefile, configured for Windows NT
MAKE=make

help:
	@echo To configure sources:
	@echo    Cygwin: \"make NT-Configure-Cygwin\" or \"make W-Configure-Cygwin\"
	@echo    GCC: \"make NT-Configure-GCC\" or \"make W-Configure-GCC\"
	@echo    MSVC: \"nmake NT-Configure\" or \"nmake W-Configure\"
	@echo Then run \"make Unicon\" to build everything
	@echo To restore Unix makefile, run:
	@echo    \"make Configure\" or \"make X-Configure\"

W-Configure-Cygwin:
	cd config/win32/cygwin && sh w-config.sh
	echo Run \"make Unicon\" to build

NT-Configure-Cygwin:
	cd config/win32/cygwin && sh config.sh
	echo Run \"make Unicon\" to build

W-Configure-GCC:
	cd config/win32/gcc && sh w-config.sh
	echo Run \"make Unicon\" to build

NT-Configure-GCC:
	cd config/win32/gcc && sh config.sh
	echo Run \"make Unicon\" to build

NT-Configure:
	cd config\win32\msvc
	config
	echo Run "nmake Unicon" to build

W-Configure:
	cd config\win32\msvc
	w-config
	echo Run "nmake Unicon" to build

Unicon: Icon-icont
	cd ipl/lib && $(MAKE)
	cd uni/unicon && $(MAKE)
	cd uni/lib && $(MAKE)
	cd uni/ivib && $(MAKE) ivib
	cd uni/ide && $(MAKE)

Icon-icont:

	sh Icon-icont.sh

Configure:
	cp config/unix/Config/top.mak ./Makefile
	@echo "NT makefile replaced with UNIX makefile; try again."


X-Configure:
	cp config/unix/Config/top.mak ./Makefile
	@echo "NT makefile replaced with UNIX makefile; try again."

Pure:
		touch Makedefs
		rm -rf icon.* bin/[a-z]* lib/[a-z]*
		cd ipl;			$(MAKE) Pure
		cd src;			$(MAKE) Pure
		cd tests;		$(MAKE) Pure
		cd config/unix; 	$(MAKE) Pure
		cd uni;			$(MAKE) Clean
