all:
	-rm *.u
	-cd ../procs && $(ICONT) -c *.icn
	cd ../procs && mv *.u ../lib
	-cd ../gprocs && $(ICONT) -c *.icn
	cd ../gprocs && mv *.u ../lib
	-cd ../mprocs && $(ICONT) -c *.icn
	cd ../mprocs && mv *.u ../lib
