# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# Labels are configured in .github/labeler.yml

name: Labeler
on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: false
